from pathlib import Path
import ast,json,shutil,math
import hashlib
import sys
root=Path(__file__).resolve().parents[2]
sources=Path(sys.argv[1])
for entry in json.loads((root/'docs/evidence/statistical-table-sources.json').read_text(encoding='utf-8')):
    assert hashlib.sha256((sources/entry['url'].rsplit('/',1)[1]).read_bytes()).hexdigest()==entry['sha256'], 'source hash mismatch'
def literals(name):
    result={}
    for node in ast.parse((sources/name).read_text()).body:
        if isinstance(node,ast.Assign) and isinstance(node.targets[0],ast.Name):
            try: result[node.targets[0].id]=ast.literal_eval(node.value)
            except (ValueError,TypeError): pass
    return result
a=literals('adfvalues.py'); j=literals('coint_tables.py')
tables=[]
for key,n in [('nc',0),('c',0),('ct',0),('c',1)]:
    tables.append(dict(small=[x*y for x,y in zip(a[f'tau_{key}_smallp'][n],[1,1,.01])],large=[x*y for x,y in zip(a[f'tau_{key}_largep'][n],[1,.1,.1,.01])],critical=a[f'tau_{key}_2010'][n]))
header='// Statistical coefficients adapted from statsmodels v0.14.6 (BSD-3-Clause).\n// Copyright (C) 2006 Jonathan E. Taylor; (c) 2006-2008 Scipy Developers;\n// (c) 2009-2018 statsmodels Developers. See LICENSE-STATSMODELS.\n// coint_tables attribution: Josef Perktold; original tables James P. LeSage.\n// Generated by docs/evidence/build-calibration-tables.py; source hashes recorded alongside.\n'
def rust(v):
    if isinstance(v,list):return '['+', '.join(rust(x) for x in v)+']'
    return repr(float(v))
text='// SPDX-License-Identifier: BSD-3-Clause\n'+header
for key,shape in [('small','[[f64; 3]; 4]'),('large','[[f64; 4]; 4]'),('critical','[[[f64; 4]; 3]; 4]')]:
    text+=f'pub(super) const {key.upper()}: {shape} = '+rust([t[key] for t in tables])+';\n'
for key in ['ejcp0','ejcp1','tjcp0','tjcp1']:
    vals=[float(x) for x in j['ss_'+key].split()][:12]
    text+=f'pub(super) const {key.upper()}: [[f64; 3]; 4] = '+rust([vals[i:i+3] for i in range(0,12,3)])+';\n'
(root/'crates/roze-ta/src/analysis/inference/calibration_tables.rs').write_text(text,encoding='utf-8')
shutil.copyfile(sources/'LICENSE.txt',root/'crates/roze-ta/LICENSE-STATSMODELS')
shutil.copyfile(sources/'manifest.json',root/'docs/evidence/statistical-table-sources.json')
# Independent scalar reference: direct polynomial powers + erfc (Rust uses Horner + statrs).
fixture=[]
limits=[(-19.04,math.inf,-1.04),(-18.83,2.74,-1.61),(-16.18,.7,-2.89),(-18.86,.92,-2.62)]
for i,table in enumerate(tables):
    lo,hi,star=limits[i]
    for statistic in [-25.,-4.,-3.,-1.,0.,3.]:
        coef=table['small'] if statistic<=star else table['large']
        z=sum(c*statistic**k for k,c in enumerate(coef))
        p=0. if statistic<lo else 1. if statistic>hi else .5*math.erfc(-z/math.sqrt(2))
        critical=[sum(c/100**k for k,c in enumerate(row)) for row in table['critical']]
        fixture.append(dict(case=i,statistic=statistic,p_value=p,nobs=100,critical=critical))
(root/'crates/roze-ta/tests/fixtures/mackinnon-reference.json').write_text(json.dumps(fixture,indent=2)+'\n',encoding='utf-8')
print('Generated licensed coefficient subset and 24 independent scalar references')
