//! Expected values were generated by the pinned independent TA-Lib C build.
use roze_ta::reference_all::{self, Request};
use serde_json::Value;

fn equivalent(expected: &Value, actual: &Value) -> bool {
    match (expected, actual) {
        (Value::Number(a), Value::Number(b)) => {
            let (a, b) = (a.as_f64().unwrap(), b.as_f64().unwrap());
            (a - b).abs() <= 2e-9 * (1.0 + a.abs())
        }
        (Value::Object(a), Value::Object(b)) => {
            a.len() == b.len()
                && a.iter()
                    .all(|(k, v)| b.get(k).is_some_and(|x| equivalent(v, x)))
        }
        _ => expected == actual,
    }
}

#[test]
fn every_talib_function_matches_independent_c_reference() {
    let data: Value = serde_json::from_str(include_str!("fixtures/talib-c-parity.json")).unwrap();
    let fixtures = data["fixtures"].as_array().unwrap();
    assert_eq!(fixtures.len(), 201 * 3);
    let mut names = std::collections::BTreeSet::new();
    for fixture in fixtures {
        names.insert(fixture["name"].as_str().unwrap());
        let mut request = fixture["request"].clone();
        request["samples"] = data["datasets"][fixture["dataset"].as_str().unwrap()].clone();
        let request: Request = serde_json::from_value(request).unwrap();
        let result = reference_all::calculate(&request).unwrap();
        let rows = result["rows"].as_array().unwrap();
        let expected = fixture["expected"].as_array().unwrap();
        assert_eq!(rows.len(), expected.len());
        for (i, (want, row)) in expected.iter().zip(rows).enumerate() {
            assert!(
                equivalent(want, &row["value"]),
                "{} {} row {i}: expected {want}, actual {}",
                fixture["name"],
                fixture["case"],
                row["value"]
            );
        }
    }
    assert_eq!(names.len(), 201);
}
