"""Compare every registered TA-Lib Rust variant against its independent C ABI.

Outputs are generated by the compiled pinned C sources, never by the Rust port.
"""
import ctypes as C
import hashlib
import json
import math
import random
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
from parity_sources import verify_source
verify_source('ta-lib')
DLL=ROOT/"target/cross-library/ta-lib-msvc/Release/ta-lib.dll"
lib=C.CDLL(str(DLL))
assert lib.TA_Initialize()==0
specs={f.findtext("Abbreviation"):f for f in ET.parse(ROOT/"target/cross-library/ta-lib/ta_func_api.xml").getroot()}
catalog=json.loads((ROOT/"docs/evidence/reference-catalog.json").read_text(encoding="utf-8"))
entries=[e for e in catalog["entries"] if e["id"].startswith("talib.")]
assert len(entries)==201
bridge=subprocess.Popen(["rtk","proxy",str(ROOT/"target/debug/examples/reference_compare.exe")],stdin=subprocess.PIPE,stdout=subprocess.PIPE,text=True,encoding="utf-8")

def bars(case,n=256):
    rng=random.Random(51881)
    out=[]
    for i in range(n):
        if case=="flat": o=c=100.; h=l=100.; v=0.
        elif case=="trend": o=100.+i*.1; c=o+.05; h=c+.1; l=o-.1; v=100.+i%5
        else:
            o=100+10*math.sin(i*.41)+rng.uniform(-4,4)
            c=o+rng.uniform(-4,4); h=max(o,c)+rng.uniform(0,4); l=min(o,c)-rng.uniform(0,4); v=10+rng.random()*100
        out.append(dict(open=o,high=h,low=l,close=c,volume=v,timestamp=i+1))
    return out

def compare(a,b):
    if a is None or b is None: return a is None and b is None
    if isinstance(a,dict): return isinstance(b,dict) and a.keys()==b.keys() and all(compare(a[k],b[k]) for k in a)
    if not math.isfinite(float(a)) or not math.isfinite(float(b)): return False
    return abs(a-b)<=2e-9*(1+abs(a))

records=[]; fixtures=[]; datasets={}
for case in ("mixed","flat","trend"):
    candles=bars(case)
    n=len(candles)
    for entry in entries:
        name=entry["name"]; spec=specs[name]
        scalar=[c["close"] for c in candles]
        if name in ("ACOS","ASIN","EXP","COSH","SINH"):
            scalar=[.4 if case=="flat" else .1+.8*(1+math.sin(i*.41))/2 for i in range(n)]
        secondary=[x*.8+math.cos(i*.37) for i,x in enumerate(scalar)]
        if name=="MAVP": secondary=[2.+float(i%29) for i in range(n)]
        values=candles if entry["input_type"]=="Candle" else list(zip(scalar,secondary)) if entry["input_type"]=="(f64, f64)" else scalar
        arrays=[]; real_index=0
        for inp in spec.findall("RequiredInputArguments/RequiredInputArgument"):
            t=inp.findtext("Type")
            if t=="Double Array":
                data=scalar if real_index==0 else secondary; real_index+=1
            else: data=[c[t.lower()] for c in candles]
            arrays.append((C.c_double*n)(*data))
        opts=[]
        for opt in spec.findall("OptionalInputArguments/OptionalInputArgument"):
            opts.append(C.c_double(float(opt.findtext("DefaultValue"))) if opt.findtext("Type")=="Double" else C.c_int(int(opt.findtext("DefaultValue"))))
        output_specs=spec.findall("OutputArguments/OutputArgument")
        outputs=[((C.c_int if o.findtext("Type")=="Integer Array" else C.c_double)*n)() for o in output_specs]
        begin=C.c_int(); count=C.c_int()
        fn=getattr(lib,"TA_"+name)
        fn.argtypes=[C.c_int,C.c_int]+[C.POINTER(C.c_double)]*len(arrays)+[type(o) for o in opts]+[C.POINTER(C.c_int)]*2+[C.POINTER(C.c_int if o.findtext("Type")=="Integer Array" else C.c_double) for o in output_specs]
        rc=fn(0,n-1,*arrays,*opts,C.byref(begin),C.byref(count),*outputs)
        if rc!=0: raise RuntimeError((name,"C reference error",rc))
        expected=[None]*n
        for i in range(count.value):
            cells=[o[i] if math.isfinite(o[i]) else None for o in outputs]
            expected[begin.value+i]=cells[0] if len(cells)==1 else {o.findtext("Name"):v for o,v in zip(output_specs,cells)}
        request={"schema_version":1,"identity":{"series_id":"parity","instrument":"TEST","timeframe":"1ms","source":"independent-C","data_version":"v1"},"operation":{"id":entry["id"],"params":entry["example_params"]},"as_of_ms":n+1,"samples":[{"at_ms":i+1,"available_at_ms":i+2,"value":v} for i,v in enumerate(values)]}
        bridge.stdin.write(json.dumps(request)+"\n"); bridge.stdin.flush()
        actual=json.loads(bridge.stdout.readline())
        if "error" in actual: diffs=[{"index":0,"error":actual["error"]}]
        else:
            diffs=[{"index":i,"expected":want,"actual":row["value"]} for i,(want,row) in enumerate(zip(expected,actual["rows"])) if not compare(want,row["value"])]
            if len(actual["rows"])!=n: raise RuntimeError("wrong output length")
        records.append({"name":name,"case":case,"status":"pass" if not diffs else "mismatch","differences":len(diffs),"first_difference":diffs[:1]})
        samples=request.pop("samples")
        key=hashlib.sha256(json.dumps(samples,separators=(",",":")).encode()).hexdigest()
        datasets[key]=samples
        fixtures.append({"source":"ta-lib","name":name,"case":case,"dataset":key,"request":request,"expected":expected})
    print(case, sum(r["status"]=="pass" for r in records if r["case"]==case),"/",len(entries),flush=True)
bridge.stdin.close(); bridge.wait(timeout=30)
manifest={"schema_version":1,"c_dll_sha256":hashlib.sha256(DLL.read_bytes()).hexdigest(),"tolerance":{"absolute":2e-9,"relative":2e-9},"records":records}
(ROOT/"docs/evidence/talib-c-parity.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8",newline="\n")
path=ROOT/"crates/roze-ta/tests/fixtures/talib-c-parity.json"
path.write_text(json.dumps({"datasets":datasets,"fixtures":fixtures},separators=(",",":"),allow_nan=False)+"\n",encoding="utf-8",newline="\n")
print("Failed entries:",sorted({r["name"] for r in records if r["status"]!="pass"}))
