"""Generate explicit typed dispatch; fail closed on unrecognised Rust signatures."""
import json
import re
from pathlib import Path
from importlib.util import spec_from_file_location, module_from_spec

ROOT = Path(__file__).resolve().parents[1]
spec = spec_from_file_location("migration", ROOT / "scripts/migrate-wickra-full.py")
migration = module_from_spec(spec)
spec.loader.exec_module(migration)
BASE = ROOT / "vendor/wickra-full/crates/wickra-core/src/indicators"
TARGET = ROOT / "crates/roze-ta/src/reference_all"


def metadata(path):
    text = path.read_text(encoding="utf-8")
    records = []
    for m in re.finditer(r"impl (Indicator|BarBuilder) for (\w+)\s*\{", text):
        kind, name = m.groups()
        body = text[m.end():migration.closing_brace(text, m.end()-1)]
        inp = re.search(r"type Input = (.*?);", body)
        output = re.search(r"type (?:Output|Bar) = (.*?);", body).group(1)
        impl = re.search(rf"impl {name}\s*\{{", text)
        if not impl:
            raise ValueError(f"Missing constructor block for {name}")
        config = text[impl.end():migration.closing_brace(text, impl.end()-1)]
        new = re.search(r"pub (?:const )?fn new\s*\((.*?)\)\s*->\s*(Result<Self>|Self)\s*\{", config, re.S)
        if not new:
            raise ValueError(f"Unrecognised constructor for {name}")
        args = []
        for arg in new.group(1).split(","):
            if arg.strip():
                pname, ptype = arg.strip().split(":", 1)
                args.append({"name": pname.strip(), "type": ptype.strip()})
        convenience = re.findall(r"pub (?:const )?fn (\w+)\(\) -> Self", config)
        doc = text[:text.find(f"pub struct {name}")]
        doc = "\n".join(re.findall(r"^/// ?(.*)$", doc, re.M))
        example = {} if not args else None
        for invocation_match in re.finditer(rf"(?:{name}|Self)::new\(([^()]*)\)", text):
            invocation = invocation_match.group(1)
            suffix = text[invocation_match.end():].lstrip()
            if args and new.group(2) != "Self" and not (suffix.startswith(".unwrap()") or suffix.startswith(".expect(")):
                continue
            parts = [p.strip() for p in invocation.split(",") if p.strip()]
            if len(parts) != len(args):
                continue
            try:
                values = []
                for part in parts:
                    if part.startswith("MaType::"):
                        values.append(part.split("::")[1])
                    else:
                        values.append(float(part.replace("_", "")) if any(c in part.lower() for c in ".e") else int(part.replace("_", "")))
                if any(a["type"] == "usize" and (v <= 0 or v > 512) for v, a in zip(values, args)):
                    continue
                example = dict(zip([a["name"] for a in args], values))
                break
            except ValueError:
                continue
        records.append({"name":name,"module":path.stem,"kind":kind,"input":inp.group(1) if inp else "Candle","output":output,"args":args,"fallible":new.group(2)!="Self","convenience":convenience,"documentation":doc,"example_params":example})
        if name == "TdRei":
            records[-1]["example_params"] = {"period":5}
    return records


def main():
    records = [item for path in sorted(BASE.glob("*.rs")) for item in metadata(path)]
    TARGET.mkdir(parents=True, exist_ok=True)
    (ROOT / "docs/evidence/wickra-constructor-inventory.json").write_text(json.dumps(records, indent=2, ensure_ascii=False)+"\n", encoding="utf-8", newline="\n")
    print("Constructor records:", len(records))
    print("Input types:", sorted({r["input"] for r in records}))
    print("Parameter types:", sorted({a["type"] for r in records for a in r["args"]}))
    if len(records) != 514:
        print("Acquisition incomplete: dispatch generation deferred")
        return
    schema_types = {
        "usize": {"type":"integer", "minimum":0, "maximum":512},
        "u32": {"type":"integer", "minimum":0, "maximum":10080},
        "i32": {"type":"integer", "minimum":-1440, "maximum":1440},
        "f64": {"type":"number", "minimum":-1e6, "maximum":1e6},
        "MaType": {"type":"string", "enum":["Sma","Ema","Wma","Dema","Tema","Trima"]},
    }
    lines = ["// Generated by scripts/generate-reference-registry.py; explicit typed dispatch.", "use super::*;", "pub(in crate::reference_all) fn build(operation: &Operation) -> Result<Box<dyn Runner>, TaError> {", "Ok(match operation.id.as_str() {"]
    entries = []
    for r in records:
        name, args = r["name"], r["args"]
        for a in args:
            if a["type"] not in schema_types:
                raise ValueError(f"unrecognised parameter type {a}")
        lines.append(f'"wickra.{name}" => {{')
        if args:
            lines.append("#[derive(Deserialize)] #[serde(deny_unknown_fields)] struct Params {")
            for a in args:
                rust_type = "w::MaType" if a["type"] == "MaType" else a["type"]
                lines.append(f'{a["name"]}: {rust_type},')
            lines.append("}")
            lines.append('let p: Params = serde_json::from_value(operation.params.clone()).map_err(|e| invalid(&format!("invalid constructor parameters: {e}")))?;')
        call = f'w::{name}::new('+", ".join("p."+a["name"] for a in args)+")"
        if r["fallible"]:
            call += ".map_err(upstream)?"
        lines.append(("indicator" if r["kind"] == "Indicator" else "builder")+"("+call+") },")
        entries.append({"id":"wickra."+name,"name":name,"input_type":r["input"],"output_type":r["output"],"kind":r["kind"],
            "parameters":{"type":"object","properties":{a["name"]:schema_types[a["type"]] for a in args},"required":[a["name"] for a in args],"additionalProperties":False},
            "example_params":r["example_params"], "formula_variant":"wickra-7ed1504-v1", "documentation":r["documentation"],
            "source":"vendor/wickra-full/crates/wickra-core/src/indicators/"+r["module"]+".rs"})
    lines.extend(['_ => return Err(TaError::new(ErrorCode::UnsupportedProfile, "unknown reference indicator")),', '})', '}'])
    (TARGET / "registry_generated.rs").write_text("\n".join(lines)+"\n", encoding="utf-8", newline="\n")
    (TARGET / "inventory.json").write_text(json.dumps(entries, indent=2, ensure_ascii=False)+"\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
