//! Stateless MCP adapter. The caller owns snapshots; formulas and validation live in the core.
use roze_ta::{
    catalog,
    engine::{self, ClosedBar, Measurement, OutputMode, SeriesIdentity, Snapshot, Stream},
    error::{ErrorCode, TaError},
};
use serde::{Deserialize, Serialize};

pub const SCHEMA_VERSION: u32 = 1;
// Leave room in the 1 MiB input frame for identity, bars and the protocol envelope.
pub const MAX_STATE_JSON_BYTES: usize = 256 * 1024;

#[derive(Clone, Debug, Deserialize, Serialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct Request {
    /// Stream tool contract version (1); independent of engine schema version (2).
    pub schema_version: u32,
    pub identity: SeriesIdentity,
    /// A fixed profile ID returned by indicator_catalog.
    pub profile_id: String,
    pub as_of_ms: i64,
    pub action: Action,
}

#[derive(Clone, Debug, Deserialize, Serialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Action {
    /// Initialize an empty stream, optionally consuming completed bars.
    Create {
        bars: Vec<ClosedBar>,
        #[serde(default)]
        output: OutputMode,
    },
    /// Restore the supplied snapshot and consume strictly newer bars.
    Advance {
        snapshot: Snapshot,
        bars: Vec<ClosedBar>,
        #[serde(default)]
        output: OutputMode,
    },
    /// Validate and inspect a snapshot without adding samples.
    Inspect { snapshot: Snapshot },
    /// Validate the snapshot, then return a fresh empty state for its identity/profile.
    Reset { snapshot: Snapshot },
}

#[derive(Debug, Serialize)]
pub struct Response {
    pub schema_version: u32,
    pub engine_schema_version: u32,
    pub implementation_version: &'static str,
    pub identity: SeriesIdentity,
    pub profile_id: String,
    pub as_of_ms: i64,
    /// Checksum of the caller's state, if this was not a create operation.
    pub previous_snapshot_checksum: Option<String>,
    pub samples_seen: u64,
    pub latest: Option<Measurement>,
    /// Series contains only rows generated by this request; latest contains at most one row.
    pub rows: Vec<Measurement>,
    pub snapshot: Snapshot,
}

fn check_state_size(snapshot: &Snapshot) -> Result<(), TaError> {
    if snapshot.payload_hex.len() > MAX_STATE_JSON_BYTES
        || serde_json::to_vec(snapshot)
            .map_err(|_| TaError::new(ErrorCode::EncodingFailed, "snapshot encoding failed"))?
            .len()
            > MAX_STATE_JSON_BYTES
    {
        return Err(TaError::new(
            ErrorCode::LimitExceeded,
            "MCP snapshot JSON exceeds 256 KiB; use the native engine for larger states",
        ));
    }
    Ok(())
}

pub fn calculate_controlled(
    request: &Request,
    mut checkpoint: impl FnMut() -> Result<(), TaError>,
) -> Result<Response, TaError> {
    checkpoint()?;
    if request.schema_version != SCHEMA_VERSION {
        return Err(TaError::new(
            ErrorCode::InvalidParameter,
            "unsupported stream tool schema",
        ));
    }
    if request.as_of_ms <= 0 {
        return Err(TaError::new(
            ErrorCode::InvalidTime,
            "as_of_ms must be positive",
        ));
    }
    request.identity.validate()?;
    let (snapshot, bars, output) = match &request.action {
        Action::Create { bars, output } => (None, bars.as_slice(), *output),
        Action::Advance {
            snapshot,
            bars,
            output,
        } => (Some(snapshot), bars.as_slice(), *output),
        Action::Inspect { snapshot } | Action::Reset { snapshot } => {
            (Some(snapshot), &[][..], OutputMode::Latest)
        }
    };
    if bars.len() > catalog::MAX_BARS {
        return Err(TaError::new(
            ErrorCode::LimitExceeded,
            "at most 4096 bars per stream call",
        ));
    }
    if matches!(&request.action, Action::Advance { .. }) && bars.is_empty() {
        return Err(TaError::new(
            ErrorCode::InvalidParameter,
            "advance requires at least one bar; use inspect for latest",
        ));
    }
    let mut stream = match snapshot {
        Some(snapshot) => {
            check_state_size(snapshot)?;
            Stream::restore(snapshot, &request.identity, &request.profile_id)?
        }
        None => Stream::new(request.identity.clone(), &request.profile_id)?,
    };
    checkpoint()?;
    if stream
        .latest()
        .is_some_and(|row| row.available_at_ms > request.as_of_ms)
    {
        return Err(TaError::new(
            ErrorCode::InvalidTime,
            "snapshot is not yet available at as_of_ms",
        ));
    }
    // Preflight every input with the same validation used by the native engine.
    let mut closed = stream.latest().map(|row| row.last_bar_closed_at_ms);
    let mut available = stream.latest().map(|row| row.available_at_ms);
    for bar in bars {
        checkpoint()?;
        engine::validate_bar(bar, request.as_of_ms, closed, available)?;
        closed = Some(bar.candle.closed_at_ms);
        available = Some(bar.available_at_ms);
    }
    if matches!(&request.action, Action::Reset { .. }) {
        stream.reset()?;
    }
    let mut rows = Vec::new();
    for bar in bars {
        checkpoint()?;
        let row = stream.update(bar, request.as_of_ms)?;
        if matches!(output, OutputMode::Series) {
            rows.push(row);
        }
    }
    if matches!(output, OutputMode::Latest) {
        rows.extend(stream.latest().cloned());
    }
    checkpoint()?;
    let next_snapshot = stream.snapshot()?;
    check_state_size(&next_snapshot)?;
    checkpoint()?;
    Ok(Response {
        schema_version: SCHEMA_VERSION,
        engine_schema_version: engine::SCHEMA_VERSION,
        implementation_version: engine::IMPLEMENTATION,
        identity: request.identity.clone(),
        profile_id: request.profile_id.clone(),
        as_of_ms: request.as_of_ms,
        previous_snapshot_checksum: snapshot.map(|s| s.checksum.clone()),
        samples_seen: stream.samples_seen(),
        latest: stream.latest().cloned(),
        rows,
        snapshot: next_snapshot,
    })
}
